# Using Pre-trained Transformers for Matching

Start out by declaring a few constants.

In [8]:
import os

import polars as pl
from transformers import AutoTokenizer

from matchescu.matching.ml.ditto.train import MAGELLAN_CONFIG

MODEL_DIR = os.path.abspath("../../models")
MODEL_NAME = "roberta-base"
DATA_DIR = os.path.abspath("../../data")
DATASETS = ["abt-buy", "amazon-google", "beer", "dblp-acm", "fodors-zagat", "itunes-amazon", "walmart-amazon"]
DATASET_CONFIG = {
    "abt-buy": {
        **MAGELLAN_CONFIG["abt-buy"],
        "Ditto F1": 0.8885,
    },
    "amazon-google": {
        **MAGELLAN_CONFIG["amazon-google"],
        "Ditto F1": 0.7410,
    },
    "beer": {
        **MAGELLAN_CONFIG["beer"],
        "Ditto F1": 0.8459,
    },
    "dblp-acm": {
        **MAGELLAN_CONFIG["dblp-acm"],
        "Ditto F1": 0.9896,
    },
    "dblp-scholar": {
        **MAGELLAN_CONFIG["dblp-scholar"],
        "Ditto F1": 0.9584,
    },
    "fodors-zagat": {
        **MAGELLAN_CONFIG["fodors-zagat"],
        "Ditto F1": 0.9814,
    },
    "itunes-amazon": {
        **MAGELLAN_CONFIG["itunes-amazon"],
        "Ditto F1": 0.9228,
    },
    "walmart-amazon": {
        **MAGELLAN_CONFIG["walmart-amazon"],
        "Ditto F1": 0.8581,
    },
}

Next, extract entity references and the ground truth from an existing CSV dataset.
The entity references are stored in an "ID" table.

In [9]:
from functools import partial
from pathlib import Path
from matchescu.matching.evaluation.datasets import MagellanDataset
from matchescu.typing import EntityReferenceIdentifier


def record_id(records, source):
    return EntityReferenceIdentifier(records[0]["id"], source)


def load_magellan_dataset(ds_name):
    ret = MagellanDataset(Path(DATA_DIR) / "magellan" / ds_name)
    ret.load_left(DATASET_CONFIG[ds_name]["traits"], partial(record_id, source="tableA"))
    ret.load_right(DATASET_CONFIG[ds_name]["traits"], partial(record_id, source="tableB"))
    ret.load_splits()
    return ret


datasets = {
    ds_name: load_magellan_dataset(ds_name)
    for ds_name in DATASETS
}

Next up, we create the comparison space.
A __binary__ comparison space is a list of pairs of entity reference identifiers.
The entity references identified in this way are deemed more suitable than others to match.
The comparison space is generated through blocking and filtering.

In [10]:
import itertools


def comparison_space(ds_name):
    return list(
        itertools.chain(
            datasets[ds_name].train_split.comparison_space,
            datasets[ds_name].valid_split.comparison_space,
            datasets[ds_name].test_split.comparison_space,
        )
    )


def ground_truth(ds_name):
    return (
            datasets[ds_name].train_split.ground_truth
            | datasets[ds_name].valid_split.ground_truth
            | datasets[ds_name].test_split.ground_truth
    )


def new_matcher(ds_name):
    ret = DittoSimilarity(
        AutoTokenizer.from_pretrained(MODEL_NAME),
        model_dir=Path(MODEL_DIR) / ds_name,
    )
    ret.load_pretrained(MODEL_NAME)
    return ret

 Next, we need to load a pretrained matcher. This requires training a model.
We're using the [Ditto classifier](https://github.com/megagonlabs/ditto/tree/master/ditto_light).
To train Ditto using a BERT model, see the `matchescu.matching.ml.ditto.train` module.

In [15]:
from sklearn.metrics import precision_score, recall_score, f1_score
from matchescu.matching.ml.ditto import DittoSimilarity


def evaluate(ds_name, threshold=None):
    cs = comparison_space(ds_name)
    gt = ground_truth(ds_name)
    gold_standard = [int(pair in gt) for pair in cs]
    entity_references = list(map(tuple, map(datasets[ds_name].id_table.get_all, cs)))
    matcher = new_matcher(ds_name)
    t = threshold or matcher.match_threshold

    # run matching algorithm on comparison space
    match_scores = {(x, y): matcher(x, y) for x, y in entity_references}
    pred = [int(v >= t) for v in match_scores.values()]
    print(f"ground truth size: {len(gold_standard)}, prediction size: {len(pred)}")
    result = DATASET_CONFIG[ds_name].copy()
    del result["traits"]
    result.update(
        {
            "dataset": ds_name,
            "matcher threshold": round(t, 2),
            "precision": round(precision_score(gold_standard, pred), 4),
            "recall": round(recall_score(gold_standard, pred), 4),
            "F1": round(f1_score(gold_standard, pred), 4),
        }
    )
    return result

It's time to run the matcher. We need to compute and store the matcher's predictions separately in order to evaluate them.

In [16]:
import time


results = []
for ds_name in DATASET_CONFIG:
    start_time = time.time()
    print("processing dataset", ds_name)
    results.append(evaluate(ds_name))
    print("finished dataset", ds_name, "time:", round(time.time() - start_time), "seconds")

display(pl.DataFrame(results).select(["dataset", "batch_size", "epochs", "matcher threshold", "precision", "recall", "F1", "Ditto F1"], Diff=(pl.col("F1") - pl.col("Ditto F1"))))

processing dataset itunes-amazon

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

ground truth size: 539, prediction size: 539
finished dataset itunes-amazon time: 37 seconds

/Users/cusi/Source/github.com/matchescu/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

shape: (1, 9)
┌───────────────┬────────────┬────────┬───────────────────┬───┬────────┬─────┬──────────┬─────────┐
│ dataset       ┆ batch_size ┆ epochs ┆ matcher threshold ┆ … ┆ recall ┆ F1  ┆ Ditto F1 ┆ Diff    │
│ ---           ┆ ---        ┆ ---    ┆ ---               ┆   ┆ ---    ┆ --- ┆ ---      ┆ ---     │
│ str           ┆ i64        ┆ i64    ┆ f64               ┆   ┆ f64    ┆ f64 ┆ f64      ┆ f64     │
╞═══════════════╪════════════╪════════╪═══════════════════╪═══╪════════╪═════╪══════════╪═════════╡
│ itunes-amazon ┆ 16         ┆ 40     ┆ 0.75              ┆ … ┆ 0.0    ┆ 0.0 ┆ 0.9228   ┆ -0.9228 │
└───────────────┴────────────┴────────┴───────────────────┴───┴────────┴─────┴──────────┴─────────┘

Finally, we construct the similarity graph. Since `matcher(a,b)!=matcher(b,a)`, the graph will be directed.

In [8]:
from matchescu.references import EntityReference
from functools import reduce
from matchescu.similarity import SimilarityGraph
from pyresolvemetrics import precision, recall, f1


# at runtime, the evaluated matcher is used directly instead of this stub
class MatcherStub:
    def __init__(self, scores: dict, threshold: float):
        self.__threshold = threshold
        self.__match_scores = scores

    @property
    def non_match_threshold(self) -> float:
        return self.__threshold

    @property
    def match_threshold(self) -> float:
        return self.__threshold

    def __call__(self, a: EntityReference, b: EntityReference) -> float:
        return self.__match_scores[(a, b)]


# effectively make the match/non-match choice binary
simg = reduce(
    lambda x, pair: x.add(*pair),
    refs,
    SimilarityGraph(
        MatcherStub(match_scores, matcher.match_threshold),
        matcher.match_threshold,
        matcher.match_threshold
    ),
)
print(repr(simg))
# the scores should be the same as the previous cell scores
cs_true_matches = set(comparison_space) & set(gt)
sim_graph_matches = frozenset(simg.matches())
print(
    "precision: %.2f, recall: %.2f, F1: %.2f"
    % (
        precision(cs_true_matches, sim_graph_matches),
        recall(cs_true_matches, sim_graph_matches),
        f1(cs_true_matches, sim_graph_matches),
    )
)

SimilarityGraph(nodes=2173, edges=733, match=733, non_match=17514, maybe=0)
precision: 0.72, recall: 0.81, F1: 0.76

In [10]:
from pyresolvemetrics import cluster_precision, cluster_recall, cluster_comparison_measure, rand_index, \
    adjusted_rand_index, twi, pair_precision, pair_recall, pair_comparison_measure
from matchescu.clustering import EquivalenceClassPartitioner, WeaklyConnectedComponents, MarkovClustering

ec_partitioner = EquivalenceClassPartitioner(comparison_space)
connected_components = WeaklyConnectedComponents(comparison_space, simg)
mcl = MarkovClustering(comparison_space, simg)

clustering_methods = [ec_partitioner, connected_components, mcl]
results = []
for clustering_method in clustering_methods:
    gt_clusters = clustering_method(cs_true_matches)
    result_clusters = clustering_method(simg.matches())
    results.append({
        "method": clustering_method.__class__.__name__,
        "Pair Precision": pair_precision(gt_clusters, result_clusters),
        "Pair Recall": pair_recall(gt_clusters, result_clusters),
        "Pair Comparison Measure": pair_comparison_measure(gt_clusters, result_clusters),
        "Cluster Precision": cluster_precision(gt_clusters, result_clusters),
        "Cluster Recall": cluster_recall(gt_clusters, result_clusters),
        "Cluster Comparison Measure": cluster_comparison_measure(gt_clusters, result_clusters),
        "Rand Index": rand_index(gt_clusters, result_clusters),
        "Adjusted Rand Index": adjusted_rand_index(gt_clusters, result_clusters),
        "Talburt-Wang Index": twi(gt_clusters, result_clusters),
    })

display(pl.DataFrame(results).transpose(include_header=True, header_name="method", column_names="method"))

shape: (9, 4)
┌────────────────────────────┬────────────────────────────┬─────────────────────┬──────────────────┐
│ method                     ┆ EquivalenceClassPartitione ┆ ConnectedComponents ┆ MarkovClustering │
│ ---                        ┆ r                          ┆ ---                 ┆ ---              │
│ str                        ┆ ---                        ┆ f64                 ┆ f64              │
│                            ┆ f64                        ┆                     ┆                  │
╞════════════════════════════╪════════════════════════════╪═════════════════════╪══════════════════╡
│ Pair Precision             ┆ 0.686047                   ┆ 0.651629            ┆ 0.71978          │
│ Pair Recall                ┆ 0.97594                    ┆ 0.973783            ┆ 0.984962         │
│ Pair Comparison Measure    ┆ 0.805711                   ┆ 0.780781            ┆ 0.831746         │
│ Cluster Precision          ┆ 0.94722                    ┆ 0.951456            ┆ 0.943456         │
│ Cluster Recall             ┆ 0.886109                   ┆ 0.894161            ┆ 0.683387         │
│ Cluster Comparison Measure ┆ 0.915646                   ┆ 0.921919            ┆ 0.792634         │
│ Rand Index                 ┆ 0.999881                   ┆ 0.999888            ┆ 0.999581         │
│ Adjusted Rand Index        ┆ 0.825516                   ┆ 0.801748            ┆ 0.398493         │
│ Talburt-Wang Index         ┆ 0.935484                   ┆ 0.939781            ┆ 0.679839         │
└────────────────────────────┴────────────────────────────┴─────────────────────┴──────────────────┘

In [16]:
refs = list(id_table)
"COL name VAL a" <-> "COL name VAL b"
print(matcher(refs[54], refs[1500]))
"COL name VAL b" <-> "COL name VAL a"
print(matcher(refs[1500], refs[54]))

0.00024045754980761558
0.00023665557091590017